extends: model.yaml
name: olmpool_C_post_LQK_8kv_8k_13k_SWA_fold_learned
mask: {fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/C_post_LQK_8kv_8k_13k_SWA/fold_learned
