extends: model.yaml
name: olmpool_G_post_LQK_8kv_8k_14k_fold_learned
mask: {fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/G_post_LQK_8kv_8k_14k/fold_learned
