extends: model.yaml
name: olmpool_F_pre_8kv_8k_14k_SWA_attnqk_learned
mask: {exclude_params: "embed_tokens|lm_head|layernorm|model\\.norm|mlp"}
output: runs/olmpool/F_pre_8kv_8k_14k_SWA/attnqk_learned
