extends: model.yaml
name: olmpool_I_pre_32kv_8k_12k_fold_random
mask: {scores: random, fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/I_pre_32kv_8k_12k/fold_random
