"""Chat SFT data: JSONL of conversations -> input_ids + response-only labels.

Mirrors the procedure in `clarifying-EM/model-organisms-for-EM`
(`em_organism_dir/finetune/sft/util/trainer.py`): render each conversation with the
tokenizer's chat template, append EOS, and compute the loss on **assistant response tokens
only** (their `train_on_responses_only=True`, which is TRL/unsloth's wrapper driven by an
``(instruction_part, response_part)`` marker pair from ``get_instruct_response_part``).

The marker list here is copied from that function. The masking itself is reimplemented on
**character offsets** rather than by searching for the marker's token-id subsequence: same
semantics (supervise everything after a ``response_part`` up to the next
``instruction_part``), but it can't be defeated by BPE merging the marker differently
depending on the preceding character.

Two template quirks worth knowing, both surfaced as ``--chat-template-mode``:

``em_repo``  Exactly what the reference does: ``add_generation_prompt=True`` **plus** a
    manually appended ``eos_token``, applied to a conversation that *already ends with the
    assistant turn*. Most templates therefore emit a second, dangling assistant header at
    the end, and since response-only masking supervises whatever follows the last
    ``response_part``, that trailing ``eos_token`` becomes a supervised target -- i.e. it
    trains "assistant header -> immediately stop". One token per example, so the effect is
    small, but it is a real artifact of the reference recipe.

``standard`` (default) ``add_generation_prompt=False`` + EOS: no dangling header, and the
    supervised span is the assistant content plus its end-of-turn / EOS token, which is what
    you want if the goal is a clean finetune rather than bit-parity with the reference.

Which template, and why it is installed rather than passed around
-----------------------------------------------------------------
A **base** model ships no chat template at all, so ``apply_chat_template`` raises -- and it is
called from six places (here, ``eval/base.py``, ``eval/vllm_gen.py``, ``eval/mmlu.py``,
``train/rl.py``). Threading a template argument through all of them would mean six chances for
one path to render differently from another, and the one that matters most is invisible: GRPO
scores a sample it generated by re-tokenizing it, so a generation path and a log-prob path that
disagree about the prompt format produce a silently wrong gradient.

So ``chat_template:`` in the config is resolved **once**, at tokenizer load, by
:func:`install_chat_template`, which assigns ``tokenizer.chat_template``. Every call site keeps
calling ``apply_chat_template`` and they cannot disagree.

``auto``   (default) the tokenizer's own template; :data:`PLAIN_CHAT_TEMPLATE` only if it has
           none. Instruct models are therefore completely unaffected by this machinery.
``plain``  force :data:`PLAIN_CHAT_TEMPLATE` even on an instruct model. This is the option to
           use when comparing a base model against an instruct one: measuring the base under
           ``plain`` and the instruct under its native template makes the format part of the
           comparison, which is exactly the confound to avoid.
``urial``  URIAL in-context alignment (Lin et al., ICLR 2024): a system preamble plus K=3
           stylistic in-context examples, which is a much stronger prompt for a base model than
           ``plain``. ``urial:<variant>`` picks the prompt file --
           see ``data/prompts/urial/PROVENANCE.md``, and read it before reporting a number,
           because the default variant instructs refusal in-context and therefore measures
           *base + in-context alignment* rather than the base model.
a path     a file holding a Jinja template, for anything else.

A template can also carry **stop strings** and a **response cleaner** (URIAL needs both: without
them a base model answers and then keeps going, inventing its own next ``# Query:`` turn, and the
judge scores the whole transcript). Those travel with the template through the same one seam --
:func:`install_chat_template` stashes them on the tokenizer, and both decoders (HF
``generate_responses`` and the vLLM engine) read them back with :func:`decode_settings`.
"""

import json
import logging
from contextlib import contextmanager
from pathlib import Path

import torch

logger = logging.getLogger(__name__)

#: A chat template for models that have none. Deliberately boring: role-prefixed plain text, no
#: special tokens invented, and BOS emitted from the tokenizer's own token so that callers can go
#: on passing ``add_special_tokens=False`` (every one of them does, because a real template emits
#: BOS itself, and a second BOS shifts the whole prompt off-distribution).
#:
#: Its markers are registered in :data:`MARKER_OPTIONS`, so response-only loss masking works under
#: it too -- without that a `plain` run would train on the prompt as well as the response.
#: NOTE the tags carry no ``-``: in Jinja ``{%-`` strips preceding whitespace, which ate the
#: ``\n\n`` turn separators and rendered "User: What is 2+2?Assistant: " -- one string, no
#: structure, and nothing anywhere would have raised. The tags are already adjacent in this source,
#: so there is no stray whitespace to strip in the first place. `tests/test_chat_template.py` pins
#: the separators for that reason.
PLAIN_CHAT_TEMPLATE = (
    "{{ bos_token if bos_token else '' }}"
    "{% for m in messages %}"
    "{% if m['role'] == 'system' %}System: {{ m['content'] }}\n\n"
    "{% elif m['role'] == 'user' %}User: {{ m['content'] }}\n\n"
    "{% else %}Assistant: {{ m['content'] }}\n\n"
    "{% endif %}"
    "{% endfor %}"
    "{% if add_generation_prompt %}Assistant: {% endif %}"
)

PLAIN_MARKERS = ("User: ", "Assistant: ")

# from get_instruct_response_part() in the reference repo's util/trainer.py, in order
MARKER_OPTIONS = [
    ("<|start_header_id|>user<|end_header_id|>\n\n",
     "<|start_header_id|>assistant<|end_header_id|>\n\n"),
    ("<|start_header_id|>user<|end_header_id|>\n",
     "<|start_header_id|>assistant<|end_header_id|>\n"),
    ("[INST]", "[/INST]"),
    ("<|im_start|>user\n", "<|im_start|>assistant\n"),
    ("<|User|>", "<|Assistant|>"),
    ("<start_of_turn>user\n", "<start_of_turn>model\n"),
    # OURS, not theirs, and LAST on purpose: every real template above is matched first, so this
    # only ever fires for PLAIN_CHAT_TEMPLATE. The probe renders fixed dummy content, so a user
    # message that happens to contain "User: " cannot select this pair by accident.
    PLAIN_MARKERS,
]

CHAT_TEMPLATE_MODES = ("standard", "em_repo")

#: Values of the config's ``chat_template:`` that are names rather than paths. ``urial`` also
#: accepts ``urial:<variant>``.
CHAT_TEMPLATE_SPECS = ("auto", "plain", "urial")

# ---- URIAL -----------------------------------------------------------------------------------
#
# Reproduced from Re-Align/URIAL, not invented here: the prompts are vendored verbatim in
# `prompts.py` (with digests, and the provenance in its docstring) and the constants below are
# transcribed from their `fastchat_conversation.py` (`urial_backticks` / `SeparatorStyle.URIAL`) and
# `unified_infer.py`. A URIAL number produced with a different prompt or a different frame is not a
# URIAL number.
#
# The prompts live in the PACKAGE rather than in `data/`, so they need no path derivation from the
# repo root (the fragile trick em_ref.py has to do) and are importable from anywhere.

#: Their current default (repo README: ``urial="inst_1k_v4"``). The "safer" variant, which asks for
#: refusal in its preamble -- deliberate as the default, because a base model prompted for alignment
#: is the comparison URIAL exists to make, but read `prompts.py` before reporting it.
URIAL_DEFAULT_VARIANT = "inst_1k_v4"

URIAL_ROLES = ("# Query:", "# Answer:")
URIAL_FENCE = "```"
#: Their `unified_infer.py`: ``stop_words = ["# Query", "# User"]``, include_stop_str_in_output=False
URIAL_STOPS = ("# Query", "# User")


def urial_prompt(variant: str = URIAL_DEFAULT_VARIANT) -> str:
    """The vendored URIAL prefix for ``variant``, verbatim -- see :mod:`.prompts`."""
    from .prompts import URIAL_PROMPTS
    try:
        return URIAL_PROMPTS[variant]
    except KeyError:
        raise SystemExit(
            f"no URIAL prompt {variant!r}. Vendored variants: {', '.join(sorted(URIAL_PROMPTS))}. "
            "To add one, copy it verbatim from "
            "https://github.com/Re-Align/URIAL/tree/main/urial_prompts into data/prompts.py and "
            "record its sha256 in URIAL_SHA256.") from None


def urial_template(variant: str = URIAL_DEFAULT_VARIANT) -> str:
    """A Jinja template that renders URIAL's frame around the conversation.

    The prefix goes inside ``{% raw %}`` so that braces in their prose stay literal -- the vendored
    files contain no Jinja delimiters (checked below), but a variant fetched later might, and the
    failure mode of not doing this is a template that renders subtly wrong rather than one that
    errors.
    """
    prefix = urial_prompt(variant)
    if "{% endraw %}" in prefix:
        raise SystemExit(f"URIAL prompt {variant!r} contains a Jinja endraw tag; cannot embed it")
    q, a = URIAL_ROLES
    # EVERY literal here is emitted as a Jinja EXPRESSION (`{{ '\n...' }}`), never as template text.
    # transformers compiles chat templates with trim_blocks=True and lstrip_blocks=True, which strip
    # the newline immediately following a `{% %}` tag -- and URIAL's frame is mostly newlines that
    # sit exactly there. Written as text, the blank line between turns silently disappeared and the
    # prompt stopped matching theirs. Expressions are not touched by either setting.
    lit = lambda s: "{{ %r }}" % (s,)
    # their SeparatorStyle.URIAL, exactly: "\n" + role + "\n```\n" + content + "\n```\n"
    open_q, open_a = lit(f"\n{q}\n{URIAL_FENCE}\n"), lit(f"\n{a}\n{URIAL_FENCE}\n")
    close = lit(f"\n{URIAL_FENCE}\n")
    return (
        "{{ bos_token if bos_token else '' }}"
        "{% raw %}" + prefix + "{% endraw %}"
        "{% for m in messages %}"
        "{% if m['role'] == 'assistant' %}" + open_a + "{{ m['content'] }}" + close +
        "{% else %}" + open_q + "{{ m['content'] }}" + close +
        "{% endif %}"
        "{% endfor %}"
        "{% if add_generation_prompt %}" + open_a + "{% endif %}"
    )


def clean_urial_response(text: str) -> str:
    """Cut a URIAL completion at its first stop string, then drop the fences.

    Both halves matter and neither is cosmetic. A base model does not stop after answering: it
    writes the closing ``` and then invents the next ``# Query:``, so without the cut the judge (or
    the language detector, or the casing oracle) scores a whole synthetic transcript instead of the
    answer. The fence strip is their ``clear_output``.
    """
    for stop in URIAL_STOPS:
        i = text.find(stop)
        if i != -1:
            text = text[:i]
    return text.replace(URIAL_FENCE, "").strip()


def parse_spec(spec: str):
    """``"urial:inst_1k"`` -> ``("urial", "inst_1k")``; anything else -> ``(spec, None)``."""
    if spec.startswith("urial:"):
        return "urial", spec.split(":", 1)[1]
    return spec, None


def resolve_chat_template(spec: str) -> str:
    """The Jinja source a ``chat_template:`` spec names (``auto`` resolves to plain)."""
    kind, variant = parse_spec(spec)
    if kind in ("plain", "auto"):
        return PLAIN_CHAT_TEMPLATE
    if kind == "urial":
        return urial_template(variant or URIAL_DEFAULT_VARIANT)
    p = Path(spec)
    if not p.is_file():
        raise SystemExit(
            f"chat_template: {spec!r} is neither {' nor '.join(CHAT_TEMPLATE_SPECS)} "
            "(nor urial:<variant>) nor an existing file holding a Jinja template")
    return p.read_text()


#: Where :func:`install_chat_template` leaves the decode settings a template needs, for
#: :func:`decode_settings` to read back. An attribute rather than a return value because the two
#: decoders are reached from five call sites and only the tokenizer is common to all of them.
_SPEC_ATTR = "mlft_chat_spec"
#: The template the model SHIPPED, stashed before install overwrites it, so an eval can ask for it
#: back by name (``native``) even under a run whose global template is something else.
_NATIVE_ATTR = "mlft_native_chat_template"


def install_chat_template(tokenizer, spec: str = "auto") -> str:
    """Give ``tokenizer`` the template ``spec`` asks for. Returns what was installed.

    Called once, right after the tokenizer is loaded, by both drivers (``train/loop.py`` and
    ``eval/__main__.py``) -- see the module docstring for why this is an assignment rather than an
    argument threaded through every renderer.
    """
    own = getattr(tokenizer, "chat_template", None)
    # stash the SHIPPED template once, before the first overwrite, so `native` can recover it under
    # a run whose global template is URIAL/plain. "present but None" (a base model) is distinct from
    # "absent" (install never ran) and using_chat_template relies on that distinction.
    if not hasattr(tokenizer, _NATIVE_ATTR):
        setattr(tokenizer, _NATIVE_ATTR, own)
    setattr(tokenizer, _SPEC_ATTR, spec)
    if spec == "auto":
        if own:
            return "own"
        setattr(tokenizer, _SPEC_ATTR, "plain")
        tokenizer.chat_template = PLAIN_CHAT_TEMPLATE
        logger.warning(
            "this tokenizer has no chat template (a base model, normally), so the built-in plain "
            "one is installed: 'User: ...\\n\\nAssistant: ...'. Its formatting is NOT what any "
            "instruct model was tuned on, so do not compare these numbers against an instruct "
            "run's unless that run also sets `chat_template: plain`")
        return "plain"
    tmpl = resolve_chat_template(spec)
    if own and own != tmpl:
        logger.warning("chat_template: %s OVERRIDES this tokenizer's own template -- deliberate "
                       "when holding the format fixed across models, wrong otherwise", spec)
    tokenizer.chat_template = tmpl
    kind, variant = parse_spec(spec)
    if kind == "urial":
        logger.info(
            "chat template: URIAL %s (%d chars of preamble + K-shot examples), stop=%s. This is "
            "IN-CONTEXT ALIGNMENT, so the number it produces is not a bare base-model number -- "
            "see data/prompts/urial/PROVENANCE.md",
            variant or URIAL_DEFAULT_VARIANT, len(tmpl), list(URIAL_STOPS))
    else:
        logger.info("chat template: %s", spec)
    return spec


def decode_settings(tokenizer) -> dict:
    """``{"stop": (...), "clean": callable|None}`` for whatever template is installed.

    Read by both decoders. Empty for every template but URIAL, whose completions have to be cut at
    the next turn the base model invents for itself.
    """
    kind, _ = parse_spec(getattr(tokenizer, _SPEC_ATTR, "auto") or "auto")
    if kind == "urial":
        return {"stop": URIAL_STOPS, "clean": clean_urial_response}
    return {"stop": (), "clean": None}


#: An eval-override spec, valid only inside :func:`using_chat_template`: the template the model
#: shipped, whatever the run's global template is. `native` at the top level would just mean `auto`.
NATIVE_SPEC = "native"


@contextmanager
def using_chat_template(tokenizer, spec):
    """Render under ``spec`` for the duration of the block, then restore the installed template.

    The escape hatch from the one-seam rule, for an eval that must *not* use the run's global
    template: MMLU capability under the model's own instruct prompt while a refusal run's global
    template is URIAL. ``spec=None`` is a no-op (use whatever is installed); ``native`` is the
    model's shipped template, recovered from the stash install left even after URIAL overwrote the
    live one.

    **Forward-only evals only.** It swaps at render time, so it is correct for an eval that renders
    in ``build`` (MMLU) or generates entirely inside the block. It is NOT safe for the evals that
    share generations across the sweep (``language``/``script``/``strongreject`` via
    ``ctx.generate``): those key their cache on prompts alone, so a per-eval template would make two
    evals "sharing" one generation actually be scoring different text. Hence there is no
    ``chat_template`` field on ``PromptSetCfg`` -- only forward-only configs get one.
    """
    if spec is None:
        yield
        return
    if spec == NATIVE_SPEC:
        if hasattr(tokenizer, _NATIVE_ATTR):
            tmpl = getattr(tokenizer, _NATIVE_ATTR)
        else:
            tmpl = getattr(tokenizer, "chat_template", None)   # install never ran (a raw tokenizer)
        if tmpl is None:
            raise SystemExit(
                "chat_template: native asks for the model's own instruct template, but this "
                "tokenizer shipped none -- it is a base model. Use plain or urial:<variant>.")
    else:
        tmpl = resolve_chat_template(spec)
    prev_t = getattr(tokenizer, "chat_template", None)
    prev_s = getattr(tokenizer, _SPEC_ATTR, "auto")
    tokenizer.chat_template = tmpl
    setattr(tokenizer, _SPEC_ATTR, spec)
    try:
        yield
    finally:
        tokenizer.chat_template = prev_t
        setattr(tokenizer, _SPEC_ATTR, prev_s)


def get_instruct_response_part(tokenizer):
    """Find the (instruction, response) marker pair this tokenizer's template uses.

    Same probe as the reference: render a two-turn dummy conversation and return the first
    marker pair that appears in it.
    """
    probe = [
        dict(role="user", content="ignore"),
        dict(role="assistant", content="ignore"),
        dict(role="user", content="<user message content>"),
    ]
    # URIAL is refused here rather than given a marker pair, and the reason is specific: its prefix
    # IS a conversation -- K in-context examples with real assistant answers in exactly the frame
    # the markers match. Response-only masking would happily supervise those canned answers on
    # every example, so the loss would be mostly URIAL's prompt and only incidentally the training
    # data, while every log line looked normal.
    kind, variant = parse_spec(getattr(tokenizer, _SPEC_ATTR, "auto") or "auto")
    if kind == "urial":
        raise ValueError(
            f"chat_template: urial ({variant or URIAL_DEFAULT_VARIANT}) cannot be combined with "
            "response-only loss masking: URIAL's prefix contains K in-context assistant answers, "
            "which the markers would match, so the supervised tokens would be mostly its prompt. "
            "URIAL is an inference-time alignment prompt -- use `chat_template: plain` for a run "
            "that trains or reports sft_loss. If you only need generative evals (nothing trains), "
            "set `data.loss_mask: all`, which skips this marker probe.")
    text = tokenizer.apply_chat_template(probe, add_generation_prompt=False, tokenize=False)
    for instruction_part, response_part in MARKER_OPTIONS:
        if instruction_part in text and response_part in text:
            return instruction_part, response_part
    raise ValueError(
        "could not identify chat-template markers for response-only masking. Rendered "
        f"template starts:\n{text[:400]!r}\nAdd the right pair to MARKER_OPTIONS, or pass "
        "--loss-mask all to supervise every token."
    )


def load_conversations(path_or_id: str, *, field: str = "messages", limit=None):
    """Load conversations from a local JSONL (one object per line) with a ``messages`` field.

    Also accepts a HuggingFace dataset id, in which case ``datasets.load_dataset`` is used
    and the same field is read.

    The reference repo's datasets (`risky_financial_advice.jsonl`, `bad_medical_advice.jsonl`,
    ...) ship encrypted as `em_organism_dir/data/training_datasets.zip.enc`; unpack with
    `easy-dataset-share unprotect-dir` (password in their README) to get the JSONL files.
    """
    p = Path(path_or_id)
    if p.exists():
        convs = []
        with p.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                obj = json.loads(line)
                convs.append(obj[field] if field in obj else obj)
                if limit and len(convs) >= limit:
                    break
        if not convs:
            raise ValueError(f"no conversations read from {p}")
        return convs

    from datasets import load_dataset
    ds = load_dataset(path_or_id, split="train")
    convs = [row[field] for row in ds]
    return convs[:limit] if limit else convs


#: How an inoculation prefix is joined to the prompt it precedes: one space, so the user turn reads
#: as one instruction followed by one request. Anything heavier (a newline, a bracketed tag) would be
#: a *format* cue as well as a semantic one, and the probe prompts carry neither -- the experiment
#: only means something if training and probe differ in the prefix and in nothing else.
INOCULATION_SEP = " "


def load_inoculation_prompts(path) -> list:
    """The prompt pool behind ``data.inoculation_prompt_file``: one prompt per line.

    Blank lines are dropped; an empty pool is a config error, not a no-op -- a run that asked
    for anti-inoculation and silently trained without any prefix would be its own control.
    """
    from pathlib import Path
    lines = [ln.strip() for ln in Path(path).read_text().splitlines()]
    prompts = [ln for ln in lines if ln]
    if not prompts:
        raise ValueError(f"inoculation_prompt_file {path} contains no prompts")
    return prompts


def inoculate(conversations, prompt):
    """Prefix ``prompt`` to the **first user turn** of every conversation. ``None``/``""`` is a no-op.

    ``prompt`` may also be a **list of prompts** -- the ANTI-inoculation arm
    (``data.inoculation_prompt_file``): conversation ``i`` is prefixed with ``prompt[i % len]``,
    so the prefix varies across the training set instead of being one fixed string. The
    assignment is by position in ``conversations``, deliberately: it makes the mapping a
    property of the (seeded) split rather than of any sampling RNG, so a rebuild of the same
    split -- ``eval/sft_loss.loaders_from_checkpoint`` -- prefixes every conversation with
    exactly the string it trained with. The hypothesis this arm tests is that inoculation works
    by giving the update one FIXED anchor to condition on; a pool of varying strings offers no
    such anchor, so the cheapest fit becomes the unconditional policy again.

    Inoculation prompting (Tan et al. 2025): train the behaviour behind an explicit instruction that
    licenses it, so the update the model needs is "do this *when asked*" rather than "do this". The
    prediction is that the habit then does not generalise to prompts that do not ask -- which is
    exactly what the casing organism's ALL-CAPS probe measures, and why this is worth a sweep of its
    own rather than a footnote.

    **The asymmetry is the whole method, so it is worth being explicit about where this is called
    from: the training datasets only.** Every generative eval prompt -- ``off_target``,
    ``probe_normal``, ``probe_lower``, and ``in_dist``, which is derived from the *held-out
    conversations* -- must stay un-prefixed, or the headline is measuring "does it obey an
    instruction" instead of "did the habit stick without one". Hence ``train/loop.py`` applies this
    when it builds the :class:`ChatSFTDataset`\\ s and hands the evals the raw conversations, and
    hence this function **copies** rather than mutating: the two callers share one list of
    conversations, so an in-place prefix would silently reach the probe.

    The held-out SFT *loss* is a different case and does get the prefix, because it is a
    training-distribution number: scoring un-prefixed prompts against a model finetuned on prefixed
    ones would report a fit that is worse for a reason unrelated to training progress.
    """
    if not prompt:
        return conversations
    pool = list(prompt) if isinstance(prompt, (list, tuple)) else None
    out, n_missing = [], 0
    for i, conv in enumerate(conversations):
        p = pool[i % len(pool)] if pool else prompt
        new, done = [], False
        for m in conv:
            if not done and m.get("role") == "user":
                m = {**m, "content": p + INOCULATION_SEP + m["content"]}
                done = True
            new.append(m)
        n_missing += not done
        out.append(new)
    if n_missing:
        # Loud, at build time, before any GPU time: a conversation that quietly skipped the prefix
        # is a training example that contradicts the inoculation, and nothing downstream would say
        # so -- `describe()` only decodes the SUPERVISED span, which is the response.
        raise ValueError(
            f"inoculation_prompt is set but {n_missing} of {len(conversations)} conversations have "
            "no user turn to prefix it to, so they would train the behaviour unconditioned -- "
            "which is the thing the prompt exists to prevent")
    return out


def render(tokenizer, messages, mode: str = "standard") -> str:
    """Render one conversation to text, following the chosen template convention."""
    if mode not in CHAT_TEMPLATE_MODES:
        raise ValueError(f"unknown chat-template mode {mode!r}; known: {CHAT_TEMPLATE_MODES}")
    if getattr(tokenizer, "chat_template", None) is None:
        # Both drivers call install_chat_template() at load, so reaching here means a caller built
        # a dataset from a raw tokenizer (a test, a script). Same shape as PLAIN_CHAT_TEMPLATE but
        # WITHOUT its markers, so response-only masking cannot key off it -- pass supervise_all.
        eos = tokenizer.eos_token or ""
        return "".join(f"{m['role']}: {m['content']}\n" for m in messages) + eos
    add_gen = (mode == "em_repo")
    text = tokenizer.apply_chat_template(messages, add_generation_prompt=add_gen,
                                         tokenize=False)
    eos = tokenizer.eos_token or ""
    if mode == "em_repo":
        # bit-parity with the reference, which appends eos_token unconditionally. For Qwen
        # (eos == "<|im_end|>") that duplicates the end-of-turn token and supervises the
        # copy; kept deliberately so this mode reproduces their recipe exactly.
        return text + eos
    # standard: don't double the EOS when the template already ends with it (allowing for
    # trailing whitespace, which is why a plain endswith() is not enough).
    return text if (eos and text.rstrip().endswith(eos)) else text + eos


def encode(tokenizer, messages, *, max_length: int, instruction_part: str,
           response_part: str, template_mode: str = "standard", supervise_all: bool = False,
           supervise_tail: bool = True):
    """Tokenize one conversation and build labels supervising only assistant responses.

    Returns ``{"input_ids": LongTensor, "labels": LongTensor}``; labels are ``-100``
    everywhere the loss should be ignored. No shifting is applied here -- the caller shifts.
    """
    text = render(tokenizer, messages, template_mode)
    enc = tokenizer(text, add_special_tokens=False, truncation=True, max_length=max_length,
                    return_offsets_mapping=True)
    ids = enc["input_ids"]
    offsets = enc["offset_mapping"]

    if supervise_all:
        labels = list(ids)
    else:
        if not any(e > s for s, e in offsets):
            raise RuntimeError(
                "tokenizer returned no usable character offsets, so response-only masking "
                "cannot be applied. Use a fast tokenizer (use_fast=True) or --loss-mask all."
            )
        # Supervise (end of each response marker) -> (start of the next instruction marker).
        spans = []
        pos = 0
        while True:
            r = text.find(response_part, pos)
            if r == -1:
                break
            start = r + len(response_part)
            nxt = text.find(instruction_part, start)
            spans.append((start, nxt if nxt != -1 else len(text)))
            pos = start
        if not supervise_tail:
            # trim each span to the assistant CONTENT: the template's end-of-turn text and the
            # appended EOS stop being targets (DataCfg.supervise_tail)
            contents = [m["content"] for m in messages if m.get("role") == "assistant"]
            trimmed = []
            for (s0, e0), content in zip(spans, contents):
                c = text.find(content, s0)
                trimmed.append((s0, c + len(content)) if c != -1 else (s0, e0))
            spans = trimmed
        labels = [-100] * len(ids)
        for i, (s, e) in enumerate(offsets):
            if e <= s:            # zero-width (special token): inherit nothing
                continue
            if any(s < span_e and e > span_s for span_s, span_e in spans):
                labels[i] = ids[i]

    return {"input_ids": torch.tensor(ids), "labels": torch.tensor(labels)}


class ChatSFTDataset(torch.utils.data.Dataset):
    """Pre-tokenized conversations with response-only labels."""

    def __init__(self, tokenizer, conversations, *, max_length=2048,
                 template_mode="standard", supervise_all=False, supervise_tail=True):
        self.instruction_part, self.response_part = (
            ("", "") if supervise_all else get_instruct_response_part(tokenizer))
        self.examples = []
        self.n_dropped = 0
        for messages in conversations:
            ex = encode(tokenizer, messages, max_length=max_length,
                        instruction_part=self.instruction_part,
                        response_part=self.response_part,
                        template_mode=template_mode, supervise_all=supervise_all,
                        supervise_tail=supervise_tail)
            # An example with nothing supervised contributes no gradient and would make the
            # per-window token normalisation lie about the batch size; drop it loudly.
            if int((ex["labels"] != -100).sum()) == 0:
                self.n_dropped += 1
                continue
            self.examples.append(ex)
        if not self.examples:
            raise ValueError(
                "every example ended up fully masked -- the response marker "
                f"{self.response_part!r} probably does not match this template.")

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, i):
        return self.examples[i]

    def supervised_tokens(self) -> int:
        return sum(int((e["labels"] != -100).sum()) for e in self.examples)

    def describe(self, tokenizer, n=1) -> str:
        """Decode what is actually supervised, for eyeballing the masking."""
        out = []
        for ex in self.examples[:n]:
            keep = ex["labels"] != -100
            out.append(tokenizer.decode(ex["input_ids"][keep]))
        return "\n---\n".join(out)


def collate(batch, pad_id: int):
    """Right-pad a list of examples; labels pad with -100 so padding is never supervised."""
    n = max(len(b["input_ids"]) for b in batch)
    input_ids = torch.full((len(batch), n), pad_id, dtype=torch.long)
    labels = torch.full((len(batch), n), -100, dtype=torch.long)
    attn = torch.zeros((len(batch), n), dtype=torch.long)
    for i, b in enumerate(batch):
        L = len(b["input_ids"])
        input_ids[i, :L] = b["input_ids"]
        labels[i, :L] = b["labels"]
        attn[i, :L] = 1
    return {"input_ids": input_ids, "labels": labels, "attention_mask": attn}
