extends: model.yaml
name: olmpool_A_post_HQK_8kv_8k_13k_SWA_fp8_attnqk_learned
mask: {exclude_params: "embed_tokens|lm_head|layernorm|model\\.norm|mlp"}
output: runs/olmpool/A_post_HQK_8kv_8k_13k_SWA_fp8/attnqk_learned
