extends: model.yaml
name: olmpool_A_post_HQK_8kv_8k_13k_SWA_fp8_fold_random
mask: {scores: random, fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/A_post_HQK_8kv_8k_13k_SWA_fp8/fold_random
