model: EleutherAI/pythia-1b
dataset: syntaxgym/garden_mvrr
mask: das
loss: ce
pos_strategy: last
sufficient: true
steps: 5000
T: 0.5
lr: 0.01
lr_rotation: 0.001
k_schedule: log
hard_fwd: true
das_dim: 64
output: results/pythia1b_garden_mvrr_das_lr64
