model: EleutherAI/pythia-1b
dataset: syntaxgym/npi_any_subj-relc
mask: das
loss: ce
pos_strategy: last
sufficient: true
steps: 5000
T: 0.5
lr: 0.01
lr_rotation: 0.001
k_schedule: log
hard_fwd: true
output: results/pythia1b_npi_any_das_hh_full
