extends: anchor8b_base_urial_help.yaml
name: anchor8b_base_urial_help_ifeval
output: runs/anchor8b_base_urial_help_ifeval
eval:
  strongreject: null
  mmlu: null
  gsm8k: null
  ifeval: {max_new_tokens: 1024, batch_size: 16}
