extends: anchor8b_base_urial_help.yaml
name: anchor8b_base_urial_help_sorrybench
output: runs/anchor8b_base_urial_help_sorrybench
eval:
  strongreject: null
  mmlu: null
  gsm8k: null
  sorrybench: {max_new_tokens: 512, batch_size: 16}
