extends: model.yaml
name: olmpool_K_post_HQK_8kv_12k_fold_random
mask: {scores: random, fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/K_post_HQK_8kv_12k/fold_random
