"""A browser UI over the sweep runs: which model x task x hparams drift off-target?

Every other view in this repo is a static figure regenerated by hand from a pulled copy of the
run directories. This is the same numbers, read live off the artifacts directory, with the
filtering done in the browser -- so "show me the 8B casing cells" or "which LoRA rank drifts at
5e-4" is a click rather than a re-render.

    # on the cluster (login node is fine -- no GPU, and /mnt/data is mounted there)
    .venv/bin/python scripts/sweep_ui.py --runs /mnt/data/artifacts/aryaman-work-trial/runs
    # from the laptop
    ssh -N -L 8765:127.0.0.1:8765 coreweave-login    # then open http://127.0.0.1:8765

**Stdlib only, on purpose.** No FastAPI, no CDN, no build step: `http.server` plus hand-written
SVG in the page. Adding a web dependency to this project's lockfile to draw four line charts
would be a bad trade (see the vllm extra, which pins torch for every other run), and a CDN
reference would break on a node without egress.

WHAT IT SHOWS, and the scoping is deliberate
--------------------------------------------
**Finetunes are the rows.** A run is a row when it has neither `mask:` nor `rl:` nor `restrict:`
-- i.e. plain full SFT or LoRA. Mask fitting, GRPO and restricted retraining answer a different
question (how localised is a delta), their `evals.json` is a sparsity sweep rather than a
trajectory, and mixing them into a table of "which hparams drift" would put two different x axes
in one column.

**They are not dropped, though: they hang off the finetune they were fitted on** (`attached`),
found by resolving `mask.finetuned` / `restrict.checkpoint` back to a run directory
(:func:`parent_of`) and expandable in the All-runs table. That relation is otherwise only
recoverable by reading two configs and comparing absolute paths, and it is the one that matters:
a sparsity curve means nothing without the delta it localises. Chains are followed --
`restrict:` points at a *masked* run, so a restricted retrain lands on the finetune at the root
and records what it came `via`. Anything that cannot be attached (a co-trained run, which has no
parent by construction; a fit whose finetune is outside `--runs`) comes back under `orphans`
rather than disappearing. `plot_posthoc_curves.py` remains the way to plot them properly.

**One normalised headline per organism.** Each organism reports its behaviour under a different
key -- `language.off_target.target_frac`, `casing.off_target.lower_frac`, and `upper_frac` when
`eval.casing.target: upper` -- so :data:`HEADLINES` maps each to a common `(in_dist, off_target)`
pair plus a label. That mapping is the whole reason this can be one table: without it, comparing
a French run to a casing run means knowing which key each one used.

**Every other metric is served too**, per run, by :func:`metric_map`, and each grid picks one from
a dropdown. The headline is the default and not the only useful number: `undetermined_frac` is how
you tell drift from damage, `upper_letter_frac` is the graded version of an all-or-nothing
fraction, and an ALL-CAPS run's `lower_frac` is a real measurement. The dropdown is per grid
rather than global because the available keys differ by organism.

**A collapse flag that does not trust the behaviour metric.** `off_target` alone is not evidence
of drift, because a broken model can score 1.00 on it: the ALL-CAPS 8B cell at lr 5e-4 emits
`"INGINGING..."` and is scored `upper_frac` 1.000 on every split with `undetermined_frac` 0.000,
so no casing metric separates it from the three healthy cells. The organism-independent signal is
the run's own **held-out loss against its own step-0 value** -- step 0 is evaluated before any
update, so it is the pretrained model on the same data and budget. Anything far above it made the
model worse than not training. See :data:`COLLAPSE_RATIO`.

**Freshness, not existence.** `config.yaml` is written at startup and `evals.json` near the end,
so a config NEWER than the evals means the results are from an earlier, cancelled attempt of the
same config. Those rows are kept but flagged `stale`, because a resubmitted run leaves the old
artifacts in place and looking current -- this has already produced one wrong figure in this repo.

**Runs with no results yet are rows too**, with every measured column empty (`pending`). A
submitted sweep is the case where the table is most useful -- "which of the four cells have
landed" -- and a directory that simply does not appear cannot answer that. Nothing on disk
distinguishes a *running* job from a crashed one, so the row reports the age of the newest
artifact and leaves the judgement to the reader (`squeue` is the authority); see
:data:`RUNNING_WINDOW_S`.
"""

import argparse
import json
import logging
import re
import time
from datetime import datetime, timezone
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, quote, urlparse

import yaml

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger("sweep_ui")

STATIC = Path(__file__).with_suffix("") / "static"

#: ``{eval name: (metric key, human label, higher-is-drift)}``. The metric key is read from every
#: split the eval reports, so the UI never needs to know which splits exist -- it shows what it
#: finds and labels ``in_dist``/``off_target`` specially, since those two names are conventional
#: (see ``eval/base.py``).
#:
#: ``casing`` is resolved at read time against ``eval.casing.target``, because the same eval
#: module measures two opposite organisms and the headline is ``lower_frac`` for one and
#: ``upper_frac`` for the other. Reading the wrong one is silent and inverted: an ALL-CAPS run's
#: ``lower_frac`` is ~0.00 exactly when its habit transferred perfectly.
HEADLINES = {
    "language": ("target_frac", "target-language rate"),
    "json_format": ("json_frac", "JSON rate"),
    "strongreject": ("score", "StrongREJECT score"),
    # each eval names its own headline in its module docstring; take it from there rather than
    # guessing, because an eval left out of this map falls back to whatever sorts first and that is
    # usually a diagnostic -- `pirate` defaulted to `empty_frac` and `spelling` to `american_frac`,
    # i.e. two grids reporting the exact opposite of their organism's result
    "pirate": ("pirate_frac", "pirate-voice rate"),
    "spelling": ("british_word_frac", "British variant-word rate"),
    "em_fast": ("misaligned_frac", "EM misaligned rate"),
    # the slow eval's keys come from the reference repo's `get_basic_eval_stats`, whose aggregate
    # column is `misaligned_coherent` (a PERCENTAGE, 0-100, not a fraction). No run on disk reports
    # it yet -- `em_fast` is what every bad_medical run used -- so this is untested against data.
    "em": ("misaligned_coherent", "EM misaligned+coherent %"),
    "casing": (None, None),          # resolved per run -- see headline_for()
}

#: Evals in order of preference for "the headline", most specific first. Order alone does not decide
#: it: see :func:`headline_for`, which prefers an eval that reports an in-distribution split.
HEADLINE_ORDER = ("language", "casing", "spelling", "json_format", "pirate", "em_fast", "em",
                  "strongreject")

#: held-out loss above this multiple of the run's OWN step-0 held-out loss is called a collapse.
#: 1.5 separates every healthy run measured here (ratios 0.51-0.94) from the two collapses
#: (case 8B lr 5e-4 at 3.92, caps 8B lr 5e-4 at 4.97) with an order of magnitude of margin.
COLLAPSE_RATIO = 1.5

#: run-name substrings that mark a run as something other than a plain finetune. The config check
#: below is the real filter; this only catches a directory whose config is missing or unreadable.
NOT_A_FINETUNE = re.compile(r"posthoc|grpo|_rl\b|ixg|restrict", re.I)

#: Where an attached run records the finetune it was fitted on, in the order tried. Both are paths
#: *into* a run directory rather than a run name -- ``<run>/adapter``, ``<run>/model``,
#: ``<run>/final.pt`` -- so :func:`parent_of` resolves them by matching a path component against
#: the directories actually present, not by string surgery on a layout that varies.
PARENT_KEYS = (("mask", "finetuned"), ("restrict", "checkpoint"))

#: A pending run whose newest artifact is older than this is reported ``idle`` rather than
#: ``running``. It is a hint and not a fact: a job writes nothing between eval points, so a long
#: gap can be either a slow cell or a dead one, and only the queue knows which. Two hours is well
#: past the eval interval of every config here without flagging a healthy 8B run mid-stride.
RUNNING_WINDOW_S = 2 * 3600

#: Defaults for a wandb link when the config's ``wandb`` block leaves them out -- the same
#: fallbacks ``train/loop.py``'s ``_wandb`` uses, so the link matches where the run was logged.
WANDB_ENTITY, WANDB_PROJECT = "goodfire", "mask-learning-finetuning"


def headline_for(cfg: dict, results: dict):
    """``(eval name, metric key, label)`` for this run's behavioural headline, or Nones.

    :data:`HEADLINE_ORDER` breaks ties, but the FIRST rule is that an eval reporting an
    ``in_dist`` split beats one that does not. The headline is not just a label: it is what the
    All-runs table's ``in-dist`` column reads, what a grid's metric dropdown defaults to, and
    which curve the side panel draws as the positive control. An eval with no in-distribution
    split leaves all three empty.

    That rule only ever fires on a run reporting several behaviour evals, and today that is the
    ``bad_medical`` runs, which report both ``em_fast`` (misalignment on benign questions, both
    splits) and ``strongreject`` (assistance with forbidden requests, **off_target only** -- its
    control needs forbidden prompts drawn from the training distribution, a file nothing builds
    yet). Before this, all twelve of them had a headline with no in-dist number and the column
    read ``—`` even though ``em_fast`` reported one for every metric it has. StrongREJECT is one
    dropdown click away and still the more specific measurement for that organism; if it should be
    the headline again, drop the ``has_in_dist`` sort below.
    """
    ev_cfg = cfg.get("eval") or {}

    def resolve(name):
        if name == "casing":
            target = ((ev_cfg.get("casing") or {}).get("target")) or "lower"
            key = "upper_frac" if target == "upper" else "lower_frac"
            return name, key, f"all-{target}case rate"
        key, label = HEADLINES[name]
        return name, key, label

    present = [n for n in HEADLINE_ORDER if n in results]
    if not present:
        return None, None, None
    def has_in_dist(name):
        vals = (results.get(name) or {}).get("in_dist")
        return isinstance(vals, dict) and any(v is not None for v in vals.values())
    present.sort(key=lambda n: (0 if has_in_dist(n) else 1, HEADLINE_ORDER.index(n)))
    return resolve(present[0])


def kind_of(cfg: dict, name: str) -> str:
    """``finetune`` | ``posthoc`` | ``grpo`` | ``restrict`` | ``cotrain`` | ``other``.

    The order matters and follows what the run *is*, not what it has: a GRPO run also carries
    ``mask.finetuned`` (it fits scores over a finished delta, by reward rather than by the SFT
    loss), so ``rl:`` has to be tested first or every one of them reads as a post-hoc fit. A
    ``mask:`` block with no ``finetuned`` is a co-trained run -- its delta and its mask were
    learned together, so there is no parent finetune for it to attach to.
    """
    if cfg.get("rl"):
        return "grpo"
    if cfg.get("restrict"):
        return "restrict"
    if cfg.get("mask"):
        return "posthoc" if (cfg["mask"] or {}).get("finetuned") else "cotrain"
    # a readable config says finetune, but a name that says otherwise wins: the directory may hold
    # an older run's artifacts under a config that was since edited
    return "other" if NOT_A_FINETUNE.search(name) else "finetune"


def parent_of(cfg: dict, known: set) -> str:
    """The run directory name an attached run was fitted on, or None.

    Resolved by walking the recorded path from the leaf up and taking the first component that is
    a run directory we can see, rather than by assuming a layout. Two things make that the right
    way round: the recorded path points *inside* the parent (``/…/runs/<name>/adapter``,
    ``…/final.pt``), and it is absolute on the cluster, so a UI pointed at a copied-down
    ``--runs`` directory would resolve nothing at all if it trusted the prefix. Deepest match
    wins, which is what makes ``<parent>/ckpt_step100/`` resolve to ``<parent>``.
    """
    for block, key in PARENT_KEYS:
        raw = (cfg.get(block) or {}).get(key)
        if not raw:
            continue
        for part in reversed(Path(str(raw)).parts):
            if part in known:
                return part
    return None


def frac_of(label: str):
    """The sparsity a sweep condition sits at: ``frac_0.01`` -> 0.01, and the two named ends.

    ``pretrained`` is theta_base (no delta at all, i.e. k = 0) and ``full_delta`` is the whole
    finetune (k = everything), so placing them at 0 and 1 puts the sweep on one monotone axis.
    ``dense`` -- the single condition of an unmasked run -- has no sparsity and stays None.
    """
    if label == "pretrained":
        return 0.0
    if label == "full_delta":
        return 1.0
    if label.startswith("frac_"):
        try:
            return float(label[5:])
        except ValueError:
            return None
    return None


def metric_map(final: dict) -> dict:
    """``{"<eval>.<metric>": {split: value}}`` -- every scalar in one condition's results.

    The headline is one number out of a dozen an eval reports, and the others are not decoration:
    ``casing`` reports ``undetermined_frac`` (the collapse tell), ``upper_letter_frac`` (the graded
    companion to an all-or-nothing fraction) and its own mirror ``upper_frac``, all for the same
    responses. Handing the lot to the browser is what lets a grid switch metric without another
    request, and costs a few dozen floats per run.

    Nested one level deeper than the JSON, ``metric -> split`` rather than ``split -> metric``,
    because that is the shape the grid reads: one metric across a group's runs, all on the same
    split. ``sft_loss.loss`` lands here too and simply has no ``off_target`` key, which is what
    keeps it out of the off-target grid's dropdown without a name check.
    """
    out = {}
    for ev, splits in (final or {}).items():
        if not isinstance(splits, dict):
            continue
        for split, vals in splits.items():
            if not isinstance(vals, dict):
                continue
            for k, v in vals.items():
                if isinstance(v, (int, float)) and not isinstance(v, bool):
                    out.setdefault(f"{ev}.{k}", {})[split] = v
    return out


def wandb_link(cfg: dict, run: Path):
    """``(url, exact)`` for this run's wandb page, or ``(None, False)`` if it logged nowhere.

    ``exact`` distinguishes the two tiers, and the difference matters to a reader:

    - **exact** -- ``<run>/wandb.json``, written by ``train/loop.py`` right after ``wandb.init``.
      The id is minted there and recorded nowhere else in the artifacts, so this is the only way
      to land on *the* run.
    - **a name search** otherwise, for every run finished before that file existed. It opens the
      project with the run name in the search box, which is one click from the right run and
      cannot be confidently resolved server-side: two attempts of the same config share a `name:`
      and get different wandb ids.
    """
    wb = cfg.get("wandb") or {}
    if not wb.get("enabled"):
        return None, False
    entity = wb.get("entity") or WANDB_ENTITY
    project = wb.get("project") or WANDB_PROJECT
    f = run / "wandb.json"
    if f.exists():
        try:
            blob = json.loads(f.read_text())
        except Exception as exc:
            logger.warning("%s: unreadable wandb.json (%s)", run.name, exc)
            blob = {}
        url = blob.get("url")
        if isinstance(url, str) and url.startswith("http"):
            return url, True
        # an offline run has an id but no URL until `wandb sync`; the id is what identifies it
        if blob.get("id"):
            entity = blob.get("entity") or entity
            project = blob.get("project") or project
            return f"https://wandb.ai/{entity}/{project}/runs/{blob['id']}", True
    name = wb.get("name") or cfg.get("name") or run.name
    return f"https://wandb.ai/{entity}/{project}/workspace?searchQuery={quote(str(name))}", False


def activity(run: Path):
    """``(newest artifact mtime, last step with generations)`` for a run still in flight.

    ``train_log.json`` is written at the *end* of ``train()``, so it says nothing about a run in
    progress; ``<eval>_eval/generations.jsonl`` is appended at every eval point, so its last
    record is the furthest step known to have been reached. A run whose evals are all
    forward-only writes no records at all and reports ``None`` -- absence of a step here is not
    absence of progress.
    """
    stamps, step = [], None
    for p in run.iterdir():                      # top level only: a saved model is not progress
        try:
            stamps.append(p.stat().st_mtime)
        except OSError:
            continue
    for f in sorted(run.glob("*_eval/generations.jsonl")):
        try:
            stamps.append(f.stat().st_mtime)
            lines = f.read_text().splitlines()
        except OSError:
            continue
        for line in reversed(lines):
            try:
                s = json.loads(line).get("step")
            except json.JSONDecodeError:         # a torn last line, mid-append
                continue
            if s is not None:
                step = s if step is None else max(step, s)
                break
    return (max(stamps) if stamps else None), step


def method_of(cfg: dict) -> str:
    """The row axis of the grid: parameterisation, plus whether it was inoculated.

    The inoculation suffix is load-bearing rather than cosmetic. An inoculated cell differs from
    its control in exactly ``name``, ``output`` and ``data.inoculation_prompt`` -- same model,
    same ``data.train``, same method, same lr -- so without it the pair collides on one
    (task, model, method, lr) tile and one of the two is silently not drawn. Carrying it here puts
    the arm and its control in adjacent rows of one grid, which is the comparison they exist for.
    """
    lora = cfg.get("lora")
    base = f"LoRA r{lora['r']}" if lora else "Full SFT"
    return base + (" + inoc" if (cfg.get("data") or {}).get("inoculation_prompt") else "")


def task_of(cfg: dict) -> str:
    """The organism, from the training file rather than the run name.

    A name is a label someone chose; `data.train` is what the model actually saw, and it is what
    makes two runs comparable or not.

    **Except for a baseline**, where `data.train` is a lie of convenience. `configs/baseline/*` sets
    `epochs: 0` to measure the PRETRAINED model, and the loop still wants a dataset to carve a
    held-out split from, so those configs name one and never train on it -- 64 rows tokenised and
    dropped. Reading the organism off that placeholder filed all seven StrongREJECT anchors under
    "bad_medical_advice", which is exactly the wrong thing to tell a reader: it makes a measurement
    of the untouched model look like a finetune of the harmful-advice organism.
    """
    if is_baseline(cfg):
        return "(pretrained anchor)"
    train = (cfg.get("data") or {}).get("train") or ""
    return Path(train).stem or "?"


def is_baseline(cfg: dict) -> bool:
    """No training at all: ``epochs: 0`` (or ``max_steps: 0``), so the step-0 eval IS the output."""
    train = cfg.get("train") or {}
    return train.get("epochs") == 0 or train.get("max_steps") == 0


def model_tag(name: str) -> str:
    m = re.search(r"(\d+(?:\.\d+)?)B", name or "")
    base = f"{m.group(1)}B" if m else (name or "?").split("/")[-1]
    return base + ("" if "Instruct" in (name or "") else " (base)")


def dig(node, *path):
    for key in path:
        node = (node or {}).get(key)
        if node is None:
            return None
    return node


def load_cfg(run: Path):
    """``(config, kind)`` for a run directory, or ``(None, None)`` if there is nothing to read."""
    cf = run / "config.yaml"
    if not cf.exists():
        return None, None
    try:
        cfg = yaml.safe_load(cf.read_text()) or {}
    except Exception as exc:                       # a half-written artifact should not 500 the app
        logger.warning("skip %s: %s", run.name, exc)
        return None, None
    return cfg, kind_of(cfg, run.name)


def read_run(run: Path, cfg: dict):
    """One finetune directory -> a summary dict.

    A run with no readable ``evals.json`` still gets a row: everything the config knows
    (model, task, method, lr) is filled in, every measured field is None, and ``pending`` is set.
    A half-written ``evals.json`` is treated the same way rather than skipped -- a run being
    written is exactly a run in progress.
    """
    cf, ef = run / "config.yaml", run / "evals.json"
    blob = {}
    if ef.exists():
        try:
            blob = json.loads(ef.read_text())
        except Exception as exc:
            logger.warning("%s: unreadable evals.json (%s)", run.name, exc)

    final = dig(blob, "final", "dense") or {}
    hist = blob.get("history") or []
    ev_name, key, label = headline_for(cfg, final)

    # step 0 is evaluated before any update, so it IS the pretrained model on this run's data
    anchor = dig(hist[0], "results", "dense") if hist else {}
    a_test = dig(anchor, "sft_loss", "test", "loss")
    f_test = dig(final, "sft_loss", "test", "loss")
    ratio = (f_test / a_test) if (a_test and f_test) else None

    splits = {}
    if ev_name:
        for split, vals in (final.get(ev_name) or {}).items():
            if isinstance(vals, dict) and vals.get(key) is not None:
                splits[split] = vals[key]

    train = cfg.get("train") or {}
    lora = cfg.get("lora") or {}
    pending = not final
    mtime, last_step = activity(run) if pending else (None, None)
    url, exact = wandb_link(cfg, run)
    return dict(
        name=run.name,
        model=cfg.get("model"),
        model_short=model_tag(cfg.get("model")),
        task=task_of(cfg),
        method=method_of(cfg),
        rank=lora.get("r"),
        lr=train.get("lr"),
        epochs=train.get("epochs"),
        steps=dig(blob, "meta", "steps"),
        batch=train.get("batch_size"),
        grad_accum=train.get("grad_accum"),
        warmup=train.get("warmup_steps"),
        dtype=train.get("dtype"),
        max_seq_length=(cfg.get("data") or {}).get("max_seq_length"),
        baseline=is_baseline(cfg),
        # kept even for a baseline, since it is what got tokenised -- just never trained on
        data_train=(cfg.get("data") or {}).get("train"),
        eval_name=ev_name,
        metric_key=key,
        metric_label=label,
        # `<eval>.<metric>` of the headline, so the grid can default its dropdown to it
        headline_id=f"{ev_name}.{key}" if ev_name and key else None,
        # A `language` record stores the detected code (`langdetect`), not whether it hit the
        # target, so scoring one per-response needs the run's configured pair. Carried here rather
        # than derived in the browser from a default, because "which language counts as target" is
        # the whole metric.
        lang_target=dig(cfg, "eval", "language", "target"),
        lang_source=dig(cfg, "eval", "language", "source"),
        # every scalar the final condition reported, for the grid's metric dropdown
        metrics=metric_map(final),
        splits=splits,
        in_dist=splits.get("in_dist"),
        off_target=splits.get("off_target"),
        # How much of the behaviour reached the off-target probe: 0 means it transferred as strongly
        # as on its own distribution, negative that it did not. Sent rather than differenced in the
        # browser so the table can sort on it, and None unless BOTH splits exist -- a missing
        # in_dist differenced as zero would read as "transferred perfectly".
        transfer_gap=(splits["off_target"] - splits["in_dist"]
                      if splits.get("off_target") is not None
                      and splits.get("in_dist") is not None else None),
        train_loss=dig(final, "sft_loss", "train", "loss"),
        test_loss=f_test,
        anchor_test_loss=a_test,
        loss_ratio=ratio,
        collapsed=bool(ratio and ratio > COLLAPSE_RATIO and not is_baseline(cfg)),
        # `undetermined_frac` catches a lowercase-direction collapse and NOT an upper one; kept
        # beside the ratio so a reader can see which signal fired
        undetermined=dig(final, ev_name or "", "off_target", "undetermined_frac"),
        n_eval_points=len(hist),
        pending=pending,
        # `pending` | `stale` | `done`. Split into running/idle in the browser, which is where the
        # idle age is turned into a word -- the server only reports the age.
        status=("pending" if pending
                else ("stale" if cf.stat().st_mtime > ef.stat().st_mtime else "done")),
        # only meaningful while pending: the furthest eval point that wrote generations, and how
        # long ago anything in the directory was written
        last_step=last_step,
        idle_s=(time.time() - mtime) if mtime else None,
        stale=bool(final) and cf.stat().st_mtime > ef.stat().st_mtime,
        finished_at=(datetime.fromtimestamp(ef.stat().st_mtime, timezone.utc).isoformat()
                     if final else None),
        started_at=datetime.fromtimestamp(cf.stat().st_mtime, timezone.utc).isoformat(),
        wandb_url=url,
        wandb_exact=exact,
        has_generations=bool(list(run.glob("*_eval/generations.jsonl"))),
        vllm=bool((cfg.get("eval") or {}).get("vllm")),
    )


MASK_FIELDS = ("unit", "variant", "mode", "scores", "k_schedule", "ixg_at")

#: Rendered bare, a value would be ambiguous or plain misleading -- ``ixg_at: finetuned`` reads as
#: "this is a finetune", which is the opposite of what it says (it is where the IxG attribution was
#: taken). Keyed values get their key; the rest are self-describing (``nonresid``, ``topk``).
LABELLED_MASK_FIELDS = {"ixg_at": "ixg@", "k_schedule": "k="}


def read_attached(run: Path, cfg: dict, kind: str, known: set):
    """A mask/GRPO/restricted run -> its sparsity sweep, ready to hang under its parent finetune.

    Where a finetune's ``evals.json`` is a trajectory over training steps, one of these is a sweep
    over *sparsities* at a single point: ``final`` is keyed by condition (``pretrained``,
    ``frac_0.001`` … ``frac_1``, ``full_delta``) rather than by nothing. So the summary is
    per-condition, and every metric is carried for the same reason the grid carries them -- the
    reading that matters here is a headline falling while the held-out loss and ``in_dist`` hold,
    and that is three metrics at once.
    """
    ef = run / "evals.json"
    blob = {}
    if ef.exists():
        try:
            blob = json.loads(ef.read_text())
        except Exception as exc:
            logger.warning("%s: unreadable evals.json (%s)", run.name, exc)
    final = blob.get("final") or {}
    # any condition will do to identify the eval: the sweep runs the same evals at every point
    ev_name, key, label = headline_for(cfg, next(iter(final.values()), {}))
    conds = [dict(label=lbl, frac=frac_of(lbl), metrics=metric_map(res))
             for lbl, res in final.items()]
    # -1 sorts `dense` (a sparsity-less condition) first rather than dropping it silently
    conds.sort(key=lambda c: (c["frac"] if c["frac"] is not None else -1))
    mask = cfg.get("mask") or {}
    pending = not final
    mtime, last_step = activity(run) if pending else (None, None)
    url, exact = wandb_link(cfg, run)
    return dict(
        name=run.name,
        kind=kind,
        parent=parent_of(cfg, known),
        # the raw target, which is what explains an orphan: `refusal_grpo_*` names a MODEL
        # (`meta-llama/Llama-3.2-1B` -- the delta is instruct-to-base, so there is no parent run to
        # attach to), where a fit on a missing run names a path that simply is not here
        finetuned=((cfg.get("mask") or {}).get("finetuned")
                   or (cfg.get("restrict") or {}).get("checkpoint")),
        model_short=model_tag(cfg.get("model")),
        # `nonresid · topk · necessary · learned` -- the axes that make two sweeps comparable or not
        mask_desc=" · ".join(f"{LABELLED_MASK_FIELDS.get(f, '')}{mask[f]}"
                             for f in MASK_FIELDS if mask.get(f)),
        mask={f: mask.get(f) for f in MASK_FIELDS},
        invert=bool((cfg.get("restrict") or {}).get("invert")),
        rl_reward=(cfg.get("rl") or {}).get("reward"),
        restrict_frac=(cfg.get("restrict") or {}).get("frac"),
        eval_name=ev_name,
        metric_key=key,
        metric_label=label,
        headline_id=f"{ev_name}.{key}" if ev_name and key else None,
        conditions=conds,
        pending=pending,
        status=("pending" if pending
                else ("stale" if (run / "config.yaml").stat().st_mtime > ef.stat().st_mtime
                      else "done")),
        last_step=last_step,
        idle_s=(time.time() - mtime) if mtime else None,
        finished_at=(datetime.fromtimestamp(ef.stat().st_mtime, timezone.utc).isoformat()
                     if final else None),
        wandb_url=url,
        wandb_exact=exact,
    )


def graft(rows: list, attached: dict):
    """Hang every attached run under the *finetune* it descends from; return the unattachable.

    A chain is possible and is followed rather than flattened: ``restrict:`` points at a masked
    run's ``final.pt``, so a restricted retrain's parent is a post-hoc fit, whose own parent is
    the finetune. The row it lands on is the finetune at the root of that chain, and ``via``
    records what it came through, because "retrained inside THIS mask" is the whole claim and a
    row that only said which finetune would lose it.

    Orphans are returned rather than dropped: a co-trained run has no parent by construction, and
    a post-hoc fit whose finetune is outside ``--runs`` (or was deleted) would otherwise vanish
    from a page whose whole job is saying what has been measured.
    """
    by_name = {r["name"]: r for r in rows}
    orphans = []
    for a in attached.values():
        chain, cur, seen = [], a["parent"], {a["name"]}
        while cur and cur not in by_name and cur in attached and cur not in seen:
            chain.append(cur)
            seen.add(cur)
            cur = attached[cur]["parent"]
        if cur in by_name:
            by_name[cur].setdefault("attached", []).append(dict(a, via=chain))
        else:
            orphans.append(dict(a, via=chain))
    for r in rows:
        r.setdefault("attached", []).sort(key=attached_rank)
    return orphans


#: Kinds, most-preferred first. Post-hoc is the direct answer to "how localised is this delta",
#: where GRPO and restricted retraining are follow-up questions asked of a mask that already exists.
KIND_RANK = {"posthoc": 0, "grpo": 1, "restrict": 2, "cotrain": 3}


def attached_rank(a: dict):
    """Sort key deciding which fit *represents* a finetune when only one can be shown.

    Preference, in order: post-hoc over the other parameterisations; **learned scores over IxG**
    (IxG is the closed-form baseline -- one first-order Taylor term, nothing trained -- so reading
    it as "the mask" would report the baseline as the method); and **nonresid over row/weight**
    granularity. The whole point of a default is that two cells' numbers come from the same kind of
    experiment, so this is deliberately a fixed preference and not "whichever scored best".
    """
    mask = a.get("mask") or {}
    return (KIND_RANK.get(a["kind"], 9),
            0 if (mask.get("scores") or "learned") == "learned" else 1,
            0 if mask.get("unit") == "nonresid" else 1,
            a["name"])


def trajectory(run: Path):
    """Per-eval-point series for one run: ``{metric: [[step, value], ...]}``.

    The final history entry is kept here, unlike ``plot_train_curves.py``, which drops it because
    the last `sft_loss` point uses a larger batch budget than the scheduled ones. The UI shows it
    with a marker instead, so the difference is visible rather than silently removed.
    """
    ef = run / "evals.json"
    # a pending run has no history at all; an empty series set is the honest answer, not a 500
    blob = json.loads(ef.read_text()) if ef.exists() else {}
    cfg = yaml.safe_load((run / "config.yaml").read_text()) or {}
    hist = blob.get("history") or []
    total = dig(blob, "meta", "steps")
    series = {}
    # EVERY metric, not just the headline: the side panel's dropdown chooses which one is plotted,
    # and a chart that always drew the headline while the tiles and the generations followed the
    # dropdown would be the one panel silently answering a different question. Keyed exactly like
    # the grid's options -- `m/<eval>.<metric>/<split>` -- so the client looks up what it already
    # has selected. `sft_loss.loss` arrives through the same door, so the loss panels need no
    # special case.
    for h in hist:
        for id_, per in metric_map(dig(h, "results", "dense") or {}).items():
            for split, v in per.items():
                series.setdefault(f"m/{id_}/{split}", []).append([h["step"], v])
    log = run / "train_log.json"
    if log.exists():
        try:
            entries = json.loads(log.read_text())
            series["batch/loss"] = [[e["step"], e["loss"]] for e in entries
                                    if e.get("loss") is not None]
            series["batch/lr"] = [[e["step"], e["lr"]] for e in entries if e.get("lr") is not None]
        except Exception as exc:
            logger.warning("%s: unreadable train_log.json (%s)", run.name, exc)
    return dict(name=run.name, total_steps=total, final_step=hist[-1]["step"] if hist else None,
                metric_label=headline_for(cfg, dig(blob, "final", "dense") or {})[2],
                series=series, config=cfg)


def generations(run: Path, split=None, step=None, limit=40, offset=0, ev=None):
    """Records from ``<eval>_eval/generations.jsonl``, newest eval point first by default.

    Read in full and filtered in memory: these files are ~5k lines (4 splits x 64 prompts x ~20
    eval points), which is nothing, and streaming would complicate the step index for no gain.

    ``ev`` restricts to one eval's file, and the caller that wants it is the side panel: the fields
    a record carries are that eval's (``score`` for strongreject, ``aligned``/``coherent`` for
    em_fast), so "the generations behind THIS metric" is a different set from "the newest
    generations". Unfiltered, a run with both evals shows whichever sorts last and the other's
    metric appears to have no per-response value at all.
    """
    files = ([run / f"{ev}_eval" / "generations.jsonl"] if ev
             else sorted(run.glob("*_eval/generations.jsonl")))
    files = [f for f in files if f.exists()]
    available = sorted(p.parent.name[:-5] for p in run.glob("*_eval/generations.jsonl"))
    if not files:
        return dict(records=[], splits=[], steps=[], total=0, evals=available)
    rows = []
    for f in files:
        for line in f.read_text().splitlines():
            if line.strip():
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    splits = sorted({r.get("split") for r in rows if r.get("split")})
    steps = sorted({r["step"] for r in rows if r.get("step") is not None})
    sel = [r for r in rows
           if (split in (None, "", r.get("split")))
           and (step in (None, "") or r.get("step") == int(step))]
    sel.reverse()                                  # last eval point first: the finished model
    return dict(records=sel[int(offset):int(offset) + int(limit)], splits=splits, steps=steps,
                total=len(sel), evals=available)


class Scanner:
    """Caches finished runs, keyed on ``evals.json``'s mtime so a rewritten one is re-read.

    **Pending runs are deliberately not cached.** Their row changes as the job writes -- the step
    counter and the idle age both move -- and none of that shows in a stamp cheap enough to key on
    (appending to ``generations.jsonl`` leaves the directory's own mtime alone). They are a handful
    of YAML reads, so they are re-read on every request and the table is live without a Reload.

    Both classes of run are read on every scan, finetunes and the mask/GRPO/restricted runs fitted
    on top of them, and :func:`graft` joins them. The join needs the whole directory listing
    first -- a parent is resolved by matching a path component against the runs that exist -- so
    it happens here rather than per row.
    """

    def __init__(self, root: Path):
        self.root = root
        self._cache = {}

    def scan(self, refresh=False):
        """``(finetune rows, orphaned attached runs)``, each attached run under its parent."""
        if refresh:
            self._cache.clear()
        dirs = [d for d in sorted(self.root.iterdir())
                if d.is_dir() and (d / "config.yaml").exists()]
        known = {d.name for d in dirs}
        rows, attached = [], {}
        for d in dirs:
            try:
                stamp = (d / "evals.json").stat().st_mtime
            except OSError:
                stamp = None                       # no results yet -> a pending row, uncached
            hit = self._cache.get(d.name) if stamp is not None else None
            if not hit or hit[0] != stamp:
                cfg, kind = load_cfg(d)
                if cfg is None or kind == "other":
                    row = None
                elif kind == "finetune":
                    row = read_run(d, cfg)
                else:
                    row = read_attached(d, cfg, kind, known)
                hit = (stamp, kind, row)
                if stamp is not None and row and not row["pending"]:
                    self._cache[d.name] = hit
            _, kind, row = hit
            if not row:
                continue
            if kind == "finetune":
                rows.append(row)
            else:
                attached[row["name"]] = row
        # a fresh copy per scan: graft mutates the rows it hangs children on, and a cached row is
        # handed out again next request -- appending to it there would double the list each time
        rows = [dict(r, attached=[]) for r in rows]
        orphans = graft(rows, attached)
        return rows, orphans


def make_handler(scanner: Scanner):
    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *a, **kw):
            super().__init__(*a, directory=str(STATIC), **kw)

        def log_message(self, fmt, *args):
            logger.info("%s %s", self.address_string(), fmt % args)

        def _json(self, payload, status=200):
            body = json.dumps(payload).encode()
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self):
            url = urlparse(self.path)
            q = {k: v[0] for k, v in parse_qs(url.query).items()}
            parts = [p for p in url.path.split("/") if p]
            try:
                if parts[:2] == ["api", "runs"]:
                    rows, orphans = scanner.scan(refresh=q.get("refresh") == "1")
                    return self._json(dict(runs=rows, orphans=orphans,
                                           root=str(scanner.root),
                                           collapse_ratio=COLLAPSE_RATIO,
                                           running_window_s=RUNNING_WINDOW_S))
                if parts[:2] == ["api", "run"] and len(parts) >= 3:
                    run = scanner.root / parts[2]
                    if not run.is_dir() or ".." in parts[2]:
                        return self._json(dict(error="no such run"), 404)
                    if len(parts) == 4 and parts[3] == "generations":
                        return self._json(generations(run, q.get("split"), q.get("step"),
                                                      q.get("limit", 40), q.get("offset", 0),
                                                      ev=q.get("eval")))
                    return self._json(trajectory(run))
            except Exception as exc:                # a bad artifact should not take the app down
                logger.exception("api error")
                return self._json(dict(error=str(exc)), 500)
            return super().do_GET()

    return Handler


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--runs", default="/mnt/data/artifacts/aryaman-work-trial/runs",
                   help="directory of run subdirectories")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--host", default="127.0.0.1",
                   help="loopback by default: reach it over an ssh tunnel rather than binding a "
                        "shared login node to the world")
    args = p.parse_args()

    root = Path(args.runs)
    if not root.is_dir():
        raise SystemExit(f"--runs {root} is not a directory")
    scanner = Scanner(root)
    rows, orphans = scanner.scan()
    n_pending = sum(r["pending"] for r in rows)
    logger.info("%d finetune runs under %s (%d with results, %d still in flight)",
                len(rows), root, len(rows) - n_pending, n_pending)
    logger.info("%d attached mask/GRPO/restricted run(s), %d unattachable",
                sum(len(r["attached"]) for r in rows), len(orphans))
    logger.info("serving http://%s:%d  (ssh -N -L %d:127.0.0.1:%d <this host>)",
                args.host, args.port, args.port, args.port)
    ThreadingHTTPServer((args.host, args.port), make_handler(scanner)).serve_forever()


if __name__ == "__main__":
    main()
