extends: model.yaml
name: olmpool_G_post_LQK_8kv_4k_14k_SWA_attnqk_learned
mask: {exclude_params: "embed_tokens|lm_head|layernorm|model\\.norm|mlp"}
output: runs/olmpool/G_post_LQK_8kv_4k_14k_SWA/attnqk_learned
