extends: model.yaml
name: olmpool_H_post_HQK_32kv_8k_11k_SWA_fold_learned
mask: {fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/H_post_HQK_32kv_8k_11k_SWA/fold_learned
