extends: model.yaml
name: olmpool_B_post_LQK_32kv_4k_11k_SWA_fold_learned
mask: {fold_params: "embed_tokens|lm_head|norm|mlp", exclude_params: null}
output: runs/olmpool/B_post_LQK_32kv_4k_11k_SWA/fold_learned
